[package]
name = "vellum"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6.4"
thiserror = "1.0.39"
regex = "1.7.1"
clap = { version = "4.2.2", features = ["derive"] }
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.2"
